### ISSUE TITLE
I need some help with tensorflow.org/js object recognition

### ISSUE THREAD

**Issue by mtrucc** [vladmandic/insightface#1]
Here is a working sample code

https://github.com/mtrucc/react-ts-fpkqes

Here is the working model

https://github.com/mtrucc/react-ts-fpkqes/tree/main/public/mask_model

This is the model I trained myself and converted using the command, it doesn't work

https://github.com/mtrucc/react-ts-fpkqes/tree/main/public/mask_model2

You can switch models by modifying the path in the code

https://github.com/mtrucc/react-ts-fpkqes/blob/6cb2ce09f4c44673098749041244b0f998f8d8f4/src/components/mask.js#L35

Install tensorflowjs

```
!pip install tensorflowjs
```

Return

```
Successfully installed flatbuffers-1.12 gast-0.4.0 keras-2.9.0 packaging-20.9 protobuf-3.20.0 tensorboard-2.9.0 tensorflow-2.9.0 tensorflow-estimator-2.9.0 tensorflowjs-3.19.0
```

Here is my conversion command in colab

```
tensorflowjs_converter --input_format=tf_saved_model \
                        --output_format=tfjs_graph_model \
  /content/gdrive/MyDrive/customTF2/data/inference_graph/saved_model \
  /content/gdrive/MyDrive/customTF2/data/inference_graph/saved_model_js
I don't know where is the problem? If you need more details, I can add.
```

I don't know where is the problem? If you need more details, I can add.

**Comment by vladmandic** [comment]
How is this related to this repository?
If it's a general question, you might want to post at TFJS forums or on stackoverflow.com.

**Comment by mtrucc** [comment]
It shouldn't matter, I just want to know how these models of yours are generated
https://github.com/vladmandic/insightface/tree/main/models
